/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#9d4300',
          container: '#f97316',
          fixed: '#ffdbca',
          'fixed-dim': '#ffb690',
          'on-fixed': '#341100',
          'on-fixed-variant': '#783200',
        },
        'on-primary': '#ffffff',
        'on-primary-container': '#582200',
        secondary: {
          DEFAULT: '#b3291b',
          container: '#fd5e49',
          fixed: '#ffdad4',
          'fixed-dim': '#ffb4a8',
          'on-fixed': '#410000',
          'on-fixed-variant': '#900c05',
        },
        'on-secondary': '#ffffff',
        'on-secondary-container': '#610000',
        tertiary: {
          DEFAULT: '#9d4135',
          container: '#e87b6b',
          fixed: '#ffdad4',
          'fixed-dim': '#ffb4a8',
          'on-fixed': '#410000',
          'on-fixed-variant': '#7e2a20',
        },
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#62160e',
        surface: {
          DEFAULT: '#fff8f3',
          container: '#fcebd7',
          'container-lowest': '#ffffff',
          'container-low': '#fff1e3',
          'container-high': '#f6e6d2',
          'container-highest': '#f1e0cc',
          dim: '#e8d8c4',
          bright: '#fff8f3',
          variant: '#f1e0cc',
          tint: '#9d4300',
        },
        'on-surface': {
          DEFAULT: '#221a0e',
          variant: '#584237',
        },
        outline: {
          DEFAULT: '#8c7164',
          variant: '#e0c0b1',
        },
        error: {
          DEFAULT: '#ba1a1a',
          container: '#ffdad6',
          'on-container': '#93000a',
        },
        'on-error': '#ffffff',
        'inverse-surface': '#382f22',
        'inverse-on-surface': '#ffeedb',
        'inverse-primary': '#ffb690',
      },
      fontSize: {
        '2xs': ['11px', { lineHeight: '15px' }],
        xs: ['13px', { lineHeight: '18px' }],
        sm: ['15px', { lineHeight: '21px' }],
        base: ['17px', { lineHeight: '25px' }],
        lg: ['19px', { lineHeight: '27px' }],
        xl: ['21px', { lineHeight: '29px' }],
        '2xl': ['25px', { lineHeight: '33px' }],
        '3xl': ['31px', { lineHeight: '37px' }],
      },
    },
  },
  plugins: [],
};
